spring.application.name=dayudita

spring.datasource.url=jdbc:postgresql://localhost:5432/dayudita_db
spring.datasource.username=postgres
spring.datasource.password=Postgres$123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
dayudita.seed-demo-data=true
